version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres-test
    restart: always
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - test-network

  redis:
    image: redis:7
    container_name: redis-test
    ports:
      - "6380:6379"
    networks:
      - test-network

volumes:
  postgres_test_data:

networks:
  test-network: